### ISSUE TITLE
Guide page not rendering properly on spring getting started page

### ISSUE THREAD

**Issue by arfatbk** [spring-guides/gs-messaging-jms#30]
On the getting started page, All include directives give this text
Unresolved directive in <stdin> - include::complete/src/main/java/hello/Receiver.java[]

**Comment by Buzzardo** [comment]
Fixed by https://github.com/spring-guides/gs-messaging-jms/commit/ff1feb6321f3a73abf983993b8b0bbb163169761 and https://github.com/spring-guides/gs-messaging-jms/commit/9c0fac9bd0218c936e5969bbd1c86215b1482d94

Thanks for letting us know. It turned out that needed to update that guide for other reasons, too. :)

**Comment by arfatbk** [comment]
It's working on. Cheers!
